### ISSUE TITLE
None of the MLIR Optimization Passes are enabled (registered 2)

### ISSUE THREAD

**Issue by velu1122** [srihari-humbarwadi/datasets#1]
Hi,

Getting the error "None of the MLIR Optimization Passes are enabled (registered 2)" after that the RetinaNet Object detection training got stuck. I use TensorFlow 2.6.0 version.
Could you please help in resolving the error.

**Comment by srihari-humbarwadi** [comment]
Can you post your hardware config?

**Comment by velu1122** [comment]
I tried the model training (https://keras.io/examples/vision/retinanet/) in Docker container (in my Windows10 laptop as well as AWS EC2 ) and got the error Got the error "None of the MLIR Optimization Passes are enabled (registered 2)". 

The Dockerfile details are, (docker image contains the below packages)

FROM tensorflow/tensorflow
RUN apt-get update -y
RUN apt-get install -y python
RUN pip install opencv-python && \
    pip install opencv-contrib-python
RUN apt install -y libgl1-mesa-glx
RUN	pip install tensorflow_datasets
RUN	pip install numpy
RUN pip install matplotlib

As discussed at https://discuss.tensorflow.org/t/none-of-the-mlir-optimization-passes-are-enabled/2247/5, now I am creating the COCO tfrecords freshly in the same docker environment and will try the Training.
However, Training works fine with Google Collab(Jupyter notebook)

Please let me know do you have any input on the mentioned error.
Thanks.

**Comment by velu1122** [comment]
The hang issue is not related to MLIR optimization, its related to batch_size and tf.data.Dataset.

When I use "batch_size > 16", it hangs on "model.fit" and continue to occupy the CPU.
If the batch_size < 16,there is no issue.

Thanks.

**Comment by srihari-humbarwadi** [comment]
Check https://github.com/srihari-humbarwadi/retinanet-tensorflow2.x, this has much better performance than the tutorial
